version: '3'
services:
  postgres:
    image: 'postgres'
    restart: always
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'mysecretpassword'
      POSTGRES_DB: 'postgres'
    ports:
      - "5432:5432"
    # volumes:
    #   - ./pgdata:/var/lib/postgresql/data
  node-app:
    build: .
    restart: on-failure
    environment:
      DB_HOST: "postgres"
      DB_USER_NAME: "postgres"
      DB_PASSWORD: "mysecretpassword"
      DB_NAME: "postgres"
    depends_on:
      - postgres
    ports:
      - "5000:5000"
      